# see https://peps.python.org/pep-0621/
[project]
name = "toutsurmoneau"
version = "0.0.14"
description = "Retrieve water meter information from Suez web site https://www.toutsurmoneau.fr/"
readme = "README.md"
requires-python = ">=3.7"
license = { file = "LICENSE" }
authors = [{ name = "Laurent MARTIN", email = "laurent.martin.l@gmail.com" }]
maintainers = [
  { name = "Laurent MARTIN", email = "laurent.martin.l@gmail.com" },
]
keywords = ["suez", "toutsurmoneau"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = ['regex', 'requests', 'datetime', 'docutils', 'pyyaml']
[project.urls]
"Homepage" = "https://github.com/laurent-martin/py-mon-eau"
"Bug Tracker" = "https://github.com/laurent-martin/py-mon-eau/issues"
[project.scripts]
toutsurmoneau = "toutsurmoneau.__main__:command_line"

[tool.bumpver]
current_version = "0.0.14"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['version = "{version}"']
"README.md" = ["{version}", "{pep440_version}"]
"src/toutsurmoneau/__init__.py" = ['^__version__ = "{version}"$']
