[tool.poetry]
name = "python-hbk"
version = "0.1.3"
description = "Python tool to work with .hbk bookmark files from Hex Workshop"
authors = ["Sergey Rivov <rvngtn@live.com>"]
homepage = "https://github.com/Rivko/python-hbk"
repository = "https://github.com/Rivko/python-hbk"
readme = "README.md"
packages = [{include = "python_hbk"}]

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
