[tool.poetry]
name = "create-jee-paper"
version = "0.1.1"
description = ""
authors = ["vaibhavblayer <vaibhavblayer@gmail.com>"]
readme = "README.md"
packages = [{include = "create_jee_paper"}]


[tool.poetry.scripts]
create-jee-paper = "create_jee_paper.main:app"

[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.7.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
