[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "coolfunc"
version = "0.1"
description = ""

requires-python = ">=3.10"
authors = [{name = "许灿标", email = "lcctoor@outlook.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: Apache Software License"]