[tool.poetry]
name = "dubletten_tool"
version = "0.2.0"
description = "APIS module for the VieCPro instance to perform manual deduplication of person instances"
authors = ["Gregor Pirgie <gregor.pirgie@oeaw.ac.at>"]

[tool.poetry.dependencies]
python = ">=3.8"
python-Levenshtein = "^0.12.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
