[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
skip-string-normalization = true

[tool.poetry]
name = "chattr-config"
version = "0.1.0"
description = ""
authors = ["Chattr <chattra23@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8"
PyYAML = "^5.4.1"
pendulum = "^2.1.2"
dataclasses = {version = "^0.8", python = ">=3.6,<3.7"}
ddtrace = "^1.9.0"
boto3 = ">=1.9.201"
singleton-decorator = "^1.0.0"
datadog = "0.44.0"
click = "~8.1.3"

[tool.poetry.dev-dependencies]
flake8 = {version = "^6.0.0", python = ">=3.8.1"}
isort = {version = "^5.9.1", python = ">=3.6.1,<4.0"}
black = {version = "^23.1.0", python = ">=3.8"}
moto = "^4.1.3"
mock = "^5.0.1"
factory-boy = "^3.2.1"
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"