[tool.poetry]
name = "test-pypi-publish-workflow"
version = "1.0.7"
description = ""
authors = ["Armand Sauzay <35524799+armand-sauzay@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "test_pypi_publish_workflow"}]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.2"


[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"

[tool.poetry.group.dev.dependencies]
python-semantic-release = "^7.32.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "test_pypi_publish_workflow/__init__.py:__version__"
]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]
# version_pattern = [
#    "README.md:rev: v{version}",
# ]
major_on_zero = false
branch = "main"
upload_to_PyPI = false
upload_to_release = true
# build_command = "pip install poetry && poetry build"
