[tool.poetry]
name = "leclerc"
version = "0.1.0"
description = ""
authors = ["Hoshang <49665855+Hoshang111@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
scipy = "^1.10.1"
numpy = "^1.24.2"
bokeh = "^3.0.3"
matplotlib = "^3.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
