[tool.poetry]
name = "penguim_analyst_guy"
version = "0.1.3"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "penguim_analyst_guy"}]

[tool.poetry.dependencies]
python = "^3.08"
pandas = "^1.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
