[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "matplotlib_coolors"
version = "4.0"
authors = [
  { name="fuysom", email="mtmfuysomztkrz@eurokool.com" },
]
description = "(Nothing to see here)"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]