[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "util_hj3415"
version = "0.7.5"
authors = [
  { name="Hyungjin Kim", email="hj3415@gmail.com" },
]
description = "The collection of utility functions for hj3415"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "python-telegram-bot",
    "requests",
    "bs4",
    "krx-hj3415",
    "selenium",
    "webdriver-manager",
    "pymongo",
]

[project.urls]
"Homepage" = "https://pypi.org/project/util_hj3415/"
"Bug Tracker" = "https://pypi.org/project/util_hj3415/"