[package]
name = "pyfnntw"
version = "0.4.0"
description = "FNNTW: Fastest Nearest Neighbor (in the) West. A fast kdtree/kNN library."
authors = ["Cavey Cool <caveycool@gmail.com>"]
repository = "https://github.com/cavemanloverboy/fnntw"
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyfnntw"
crate-type = ["cdylib"]

[dependencies]
fnntw = { path = "local_dependencies/fnntw", features = ["no-position", "sqrt-dist2"]}
pyo3 = { version = "0.16.5", features = ["extension-module"] }
ouroboros = "0.15.2"
numpy = "0.16.2"
rayon = "1.5.3"
ndarray = { version = "0.15.6", features = ["rayon"] }
concat-idents = "1.1.4"
tcmalloc = "0.3.0"

[profile.release]
lto = "fat"
codegen-units = 1
