[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "awModelUpload"
version = "0.0.3"
authors = [
  { name="OOK", email="omerkutsal@gmail.com" },
]
description = "I-WUNDER DSW"
readme = "README.md"
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "selenium==4.8.2",
]