[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "inspect_dense"
version = "0.2.4"
description = "A tool for recursively describing all files in a directory."
authors = ["Justin Riddiough <justin@visioninit.dev>"]
license = "APACHE-2.0"
homepage = "https://github.com/neural-loop/inspect_dense"
repository = "https://github.com/neural-loop/inspect_dense"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
gitignore-parser = "^0.1.3"
chardet = "^5.1.0"

[tool.poetry.scripts]
inspect-dense = "inspect_dense.getcode:main"
