[tool.poetry]
name = "litelearn"
version = "0.2.6"
description = "a python library for quickly building and evaluating models"
authors = ["Aviad Rozenhek <aviadr1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.5"
llvmlite = "^0.39.1" # needed because of issues in version 0.34
numba = "^0.56" # needed because of issues in version 0.47
catboost = "^1.1.1"
shap = "^0.41.0"
seaborn = "^0.11.2"
scikit-learn = "^1.0.2"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
jupyterlab = "^3.5.0"
ipywidgets = "^8.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
