[project]
name = "importfiler"
version = "0.0.1"
description = "Profile the import time of a module."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE.txt"}
keywords = ["cli", "development"]
authors = [
  {name = "Mario Corchero", email = "mariocj89@gmail.com" }
]

maintainers = [
  {name = "Mario Corchero", email = "mariocj89@gmail.com" }
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  "typer[all]"
]

[project.urls]
"Homepage" = "https://github.com/mariocj89/importfiler"
"Source" = "https://github.com/mariocj89/importfiler"

[project.scripts]
importfiler = "importfiler:main"

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"
