[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "pgtg_widgets"
version = "0.0.6"
authors = [
  { name="Tea-Guardian", email="grammarline@yandex.ru" },
]
description = "widgets for pygame"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/TeaGuardian/pgtg_widgets"
"Bug Tracker" = "https://github.com/TeaGuardian/pgtg_widgets/issues"
