[tool.poetry]
name = "VisNet1D"
version = "0.1.3"
description = "A visualation tool for 1D networks"
authors = ["Alex <adrysdale@protonmail.com>"]
license = "GPLv3+"
repository = "https://gitlab.com/abdrysdale/visnet1d"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
plotly = "^5.7.0"
dash = "^2.3.1"
numpy = "^1.22.3"
pandas = "^1.4.2"
pillow = "^9.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
