[tool.poetry]
name = "qtpy-led"
version = "0.1.2"
description = "Simple LED widget for QyPt"
authors = ["crash8229 <mu304007@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/crash8229/qtpy_led"
packages = [{include = "qtpy_led"}]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.2"
PyAutoGUI = "^0.9.53"
QtPy = "^2.3.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.0.1"
black = "^23.1.0"
types-PyAutoGUI = "^0.9.3.5"
PySide6 = { version = "^6.4.2", python = ">=3.7, <3.12" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
