[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mysqld-integration-test"
version = "0.0.1"
authors = [{name = "Jason Camp", email = "me@jason.camp"}]
license = {text = "GPL"}
description = "mysqld-integration-test is a python module that creates a temporary mysqld instance to use for testing your application."
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11"
]

dependencies = [
    "mysql-connector-python == 8.0.32",
    "pyyaml == 5.4.1",
]

requires-python = ">=3.7"

[project.optional-dependencies]
tests = [
  "pytest == 7.2.1",
  "pytest-env == 0.8.1",
  "pytest-cov == 4.0.0",
  "coverage == 7.2.1",
]

[project.urls]
Homepage = "https://github.com/jasondcamp/mysqld-integration-test"

