[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aishell"
version = "2023.03.02"
description = ""
authors = []
readme = "README.md"

[tool.pyright]
typeCheckingMode = "strict"
pythonPlatform = "All"
venvPath = "./.venv"
stubPath = "./.type_stubs"
include = [ "./*",]
exclude = [ "**/node_modules", "**/__pycache__",]
useLibraryCodeForTypes = true
reportMissingTypeStubs = false
reportUnknownMemberType = false

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 2
split_before_logical_operator = true
column_limit = 119
allow_split_before_dict_value = false

[tool.ruff]
line-length = 119
select = [ "PLE", "PLR", "PLW", "E", "W", "F", "I", "Q", "C", "B",]

[tool.poetry.dependencies]
python = "^3.8"
poetry = "^1.3.1"
revchatgpt = "^2.2.7"
openai = "^0.26.5"
pydantic = "^1.10.4"
pyright = "^1.1.294"

[tool.poetry.scripts]
aishell = "aishell:main"

[tool.ruff.flake8-quotes]
inline-quotes = "single"
docstring-quotes = "single"
multiline-quotes = "single"

[tool.poetry.dependencies.typer]
extras = [ "all",]
version = "^0.7.0"

[tool.poetry.group.dev.dependencies]
toml = "^0.10.2"
yapf = "^0.32.0"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
invoke = "^1.7.3"
ruff = "^0.0.199"
types-invoke = "^1.7.3.16"
types-toml = "^0.10.8.1"
pyright = "^1.1.294"
